### ISSUE TITLE
Feature: User can view the landing page

### ISSUE THREAD

**Issue by e-bales** [e-bales/curate#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the home page when connecting to https://curate.elibales.dev/

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will see the home page (static at this point), which matches the wireframe below.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/e-bales/curate/assets/132625085/71cf06ec-cb9f-47e5-979d-d369e0b00ab7)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create the header component, which will be used across all pages on my application.
  - [x] Can type into the search bar, but will be non-functional as of now.
  - [x] Sign-In is clickable, but non-functional as of now.
- [x] Create the middle 'carousel' component, currently with just one image and the two arrows to its side.
  - [x] Arrows are clickable, but non-functional as of now.
  - [x] Image has appropriate drop-shadow.
  - [x] Test image component with different sized images, ensure the arrows stay in the same place for all sizes. 
  - [x] Ensure artist text appears in the correct place for each image, despite different image dimensions. 
- [x] Add login message below carousel, which will disappear if the user is logged in.
