### ISSUE TITLE
Feature: User can view the log-in modal.

### ISSUE THREAD

**Issue by e-bales** [e-bales/curate#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on Sign In in the header and the login modal will appear.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the sign in text, the modal will appear and the rest of the page will darken.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/e-bales/curate/assets/132625085/31115a59-f972-419e-80a1-c9120e4c45c6)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create the page darkening component, which I can reuse across my site whenever I open a modal.
  - [x] Ensure it covers all of the page EXCEPT the modal, perhaps z = 1 for the darkening, and z = 2 for the component.
- [x] Create the sign in modal, with a simple form that accepts a username and password.
  - [x] Currently, clicking LOGIN will do nothing, functionality will be added later.
  - [x] Include the subtext at the bottom, which will be how the user navigates to creating an account.
- [x] Create a state variable that tracks whether the user is attempting to log in or not, which is set to true when the user clicks 'Sign In' in the nav bar, so that when we re-render we may render the login modal.
- [x] If the user clicks anywhere outside the modal (i.e. screen darkening) then set the state variable to false to close the modal.
- [x] Test both the opening and closing of the modal to ensure it works.
