### ISSUE TITLE
Feature: User can view the sign up modal.

### ISSUE THREAD

**Issue by e-bales** [e-bales/curate#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account, by clicking the Sign Up text on the Log In form.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can see the Sign Up modal and enter a username and a password, which they have to retype to confirm. If the passwords do not match, then an error message will be displayed. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/e-bales/curate/assets/132625085/11bee2d0-e47a-4709-89f1-e303846f65b8)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create the sign up component, which is similar to the login component, but with an extra password field.
- [x] Reuse the state variable from the login modal. If the user is trying to login, set the variable to 1, if they are trying to sign up, set the variable to 2, if neither, set it to 0.
  - [x] By clicking on the Sign Up text in the login modal, change the state variable to 2 to swap forms.
  - [x] Clicking outside the form, set the variable to 0.
  - [x] Clicking back on the Log In text at the bottom of the modal will change the variable back to 1.
- [x] Currently, the form will be non-functional, besides checking the two passwords are the same.
